"""coach chat message token usage

Revision ID: 06f70acc51b6
Revises: b7c1d9e24a10
Create Date: 2026-10-04 12:03:29.830655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06f70acc51b6'
down_revision: Union[str, None] = 'b7c1d9e24a10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coach_chat_messages', sa.Column('llm_model', sa.String(length=64), nullable=True))
    op.add_column('coach_chat_messages', sa.Column('prompt_tokens', sa.Integer(), nullable=True))
    op.add_column('coach_chat_messages', sa.Column('cached_tokens', sa.Integer(), nullable=True))
    op.add_column('coach_chat_messages', sa.Column('completion_tokens', sa.Integer(), nullable=True))
    op.add_column('coach_chat_messages', sa.Column('reasoning_tokens', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coach_chat_messages', 'reasoning_tokens')
    op.drop_column('coach_chat_messages', 'completion_tokens')
    op.drop_column('coach_chat_messages', 'cached_tokens')
    op.drop_column('coach_chat_messages', 'prompt_tokens')
    op.drop_column('coach_chat_messages', 'llm_model')
    # ### end Alembic commands ###
