"""add training_block phase_session_baseline

Revision ID: 1885fef8ec02
Revises: ae98d105130e
Create Date: 2026-09-01 15:45:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1885fef8ec02'
down_revision: Union[str, None] = 'ae98d105130e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'training_blocks',
        sa.Column('phase_session_baseline', sa.Integer(), server_default=sa.text('0'), nullable=False),
    )
    # ### end Alembic commands ###
    # Existing rows backfill to 0 (the server_default) -- for a block
    # already mid-phase, this is a one-time approximation: it can't
    # recover how many real sessions were already "spent" on this phase's
    # own earlier (pre-migration) transitions, so count_sessions_completed_
    # in_phase will read as the block's full lifetime total until its next
    # transition, when the counter starts tracking correctly. Acceptable
    # here (pre-launch, no real user base yet) -- the alternative (trying
    # to reconstruct history from phase_started_at, the very field this
    # migration exists because it can't be trusted for this) isn't.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_blocks', 'phase_session_baseline')
    # ### end Alembic commands ###
