"""coach memory facts

Revision ID: 274f466860f9
Revises: 06f70acc51b6
Create Date: 2026-10-04 12:55:53.407399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '274f466860f9'
down_revision: Union[str, None] = '06f70acc51b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coach_memory_facts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coach_memory_facts_user_id'), 'coach_memory_facts', ['user_id'], unique=False)
    op.create_table('coach_memory_states',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('summarized_until', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coach_memory_states')
    op.drop_index(op.f('ix_coach_memory_facts_user_id'), table_name='coach_memory_facts')
    op.drop_table('coach_memory_facts')
    # ### end Alembic commands ###
