"""add set completions table and exercise weight tracking fields

Revision ID: 35811ecfe0cf
Revises: bea9b567adda
Create Date: 2026-08-04 11:29:38.514457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35811ecfe0cf'
down_revision: Union[str, None] = 'bea9b567adda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('set_completions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('training_session_id', sa.UUID(), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('reps_completed', sa.Integer(), nullable=True),
    sa.Column('duration_seconds_completed', sa.Integer(), nullable=True),
    sa.Column('suggested_weight_kg', sa.Float(), nullable=True),
    sa.Column('was_weight_adjusted_manually', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('feedback', sa.Enum('easy', 'normal', 'hard', 'max', name='set_feedback', native_enum=False), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('set_number >= 1', name='ck_set_completions_set_number_positive'),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['training_session_id'], ['training_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('training_session_id', 'exercise_id', 'set_number', name='uq_set_completions_session_exercise_set')
    )
    op.create_index(op.f('ix_set_completions_exercise_id'), 'set_completions', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_set_completions_training_session_id'), 'set_completions', ['training_session_id'], unique=False)
    op.create_index(op.f('ix_set_completions_user_id'), 'set_completions', ['user_id'], unique=False)
    op.add_column('exercises', sa.Column('tracks_weight', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('exercises', sa.Column('bodyweight_ratio', sa.Float(), nullable=True))
    # ### end Alembic commands ###
    # NOTE: autogenerate also proposed dropping 'ix_outbox_events_unpublished'
    # (same pre-existing drift noted in d45a3d5462bb: that partial index
    # exists in the DB but isn't declared on the OutboxEvent model) --
    # unrelated to this migration's purpose, left untouched here too.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercises', 'bodyweight_ratio')
    op.drop_column('exercises', 'tracks_weight')
    op.drop_index(op.f('ix_set_completions_user_id'), table_name='set_completions')
    op.drop_index(op.f('ix_set_completions_training_session_id'), table_name='set_completions')
    op.drop_index(op.f('ix_set_completions_exercise_id'), table_name='set_completions')
    op.drop_table('set_completions')
    # ### end Alembic commands ###
