"""add privacy_consent_at to users

Revision ID: 3c1ea6d0c1f4
Revises: 585260902ca0
Create Date: 2026-08-08 14:38:51.955152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c1ea6d0c1f4'
down_revision: Union[str, None] = '585260902ca0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('privacy_consent_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'privacy_consent_at')
    # ### end Alembic commands ###
