"""ice and game report

Revision ID: 51367b0109f9
Revises: aee5a3b71ead
Create Date: 2026-10-08 10:10:30.095777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '51367b0109f9'
down_revision: Union[str, None] = 'aee5a3b71ead'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('day_plans', sa.Column('report_reminder_sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('training_diary_entries', sa.Column('reported_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('training_diary_entries', sa.Column('skipped', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('training_diary_entries', sa.Column('duration_minutes', sa.SmallInteger(), nullable=True))
    op.add_column('training_diary_entries', sa.Column('effort', sa.Enum('easy', 'normal', 'hard', name='ice_effort', native_enum=False, length=16), nullable=True))
    op.add_column('training_diary_entries', sa.Column('highlights', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('training_diary_entries', sa.Column('game_result', sa.Enum('win', 'draw', 'loss', name='game_result', native_enum=False, length=16), nullable=True))
    op.add_column('training_diary_entries', sa.Column('goals', sa.SmallInteger(), nullable=True))
    op.add_column('training_diary_entries', sa.Column('assists', sa.SmallInteger(), nullable=True))
    op.add_column('training_diary_entries', sa.Column('shots', sa.SmallInteger(), nullable=True))
    op.add_column('training_diary_entries', sa.Column('self_rating', sa.SmallInteger(), nullable=True))
    op.add_column('training_diary_entries', sa.Column('work_on', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('training_diary_entries', sa.Column('share_rating_with_coach', sa.Boolean(), server_default='false', nullable=False))
    op.create_check_constraint(
        'ck_training_diary_entries_self_rating', 'training_diary_entries', 'self_rating BETWEEN 1 AND 5'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_training_diary_entries_self_rating', 'training_diary_entries', type_='check')
    op.drop_column('training_diary_entries', 'share_rating_with_coach')
    op.drop_column('training_diary_entries', 'work_on')
    op.drop_column('training_diary_entries', 'self_rating')
    op.drop_column('training_diary_entries', 'shots')
    op.drop_column('training_diary_entries', 'assists')
    op.drop_column('training_diary_entries', 'goals')
    op.drop_column('training_diary_entries', 'game_result')
    op.drop_column('training_diary_entries', 'highlights')
    op.drop_column('training_diary_entries', 'effort')
    op.drop_column('training_diary_entries', 'duration_minutes')
    op.drop_column('training_diary_entries', 'skipped')
    op.drop_column('training_diary_entries', 'reported_at')
    op.drop_column('day_plans', 'report_reminder_sent_at')
    # ### end Alembic commands ###
