"""add user has_seen_onboarding_tour flag

Revision ID: 57e13feb4475
Revises: b4cc3e894f39
Create Date: 2026-08-10 15:40:45.861991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57e13feb4475'
down_revision: Union[str, None] = 'b4cc3e894f39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('has_seen_onboarding_tour', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'has_seen_onboarding_tour')
    # ### end Alembic commands ###
