"""add reminder preference and timezone to users, reminder_sent_at to day_plans

Revision ID: 585260902ca0
Revises: a60cb7019692
Create Date: 2026-08-07 17:01:19.640288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '585260902ca0'
down_revision: Union[str, None] = 'a60cb7019692'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('day_plans', sa.Column('reminder_sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('timezone', sa.String(length=64), server_default='UTC', nullable=False))
    op.add_column('users', sa.Column('reminder_preference', sa.Enum('none', 'morning', 'evening', name='reminder_preference', native_enum=False), server_default='none', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reminder_preference')
    op.drop_column('users', 'timezone')
    op.drop_column('day_plans', 'reminder_sent_at')
    # ### end Alembic commands ###
