"""add skill required_level

Revision ID: 59bb0f21b7c2
Revises: df9228b5f7f9
Create Date: 2026-08-07 12:37:11.245018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59bb0f21b7c2'
down_revision: Union[str, None] = 'df9228b5f7f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


TIER_1_SKILLS = [
    "Взрывной старт",
    "Выносливость",
    "Баланс и устойчивость",
    "Мобильность",
    "Катание",
    "Скоростная выносливость",
]
TIER_8_SKILLS = ["Силовая борьба", "Обводка", "Координация и реакция"]
TIER_15_SKILLS = ["Сила броска", "Игровое чтение"]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skills', sa.Column('required_level', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###

    # Data migration: tier the 11 existing skills by required_level.
    # Checked against the actual `skills` rows in dev -- all 11 names below
    # matched the DB verbatim (case/spacing/wording identical), so this is
    # a straight name lookup, not a judgment call. TIER_1_SKILLS needs no
    # UPDATE (the column default of 1 already covers them); listed here
    # anyway so the three tiers are visible together in one place.
    skills = sa.table("skills", sa.column("name", sa.String), sa.column("required_level", sa.Integer))
    op.execute(skills.update().where(skills.c.name.in_(TIER_8_SKILLS)).values(required_level=8))
    op.execute(skills.update().where(skills.c.name.in_(TIER_15_SKILLS)).values(required_level=15))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skills', 'required_level')
    # ### end Alembic commands ###
