"""team stats reminder

Revision ID: 678ddd846e38
Revises: 4bf782b412df
Create Date: 2026-10-08 10:47:07.740206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '678ddd846e38'
down_revision: Union[str, None] = '4bf782b412df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('stats_reminder_sent_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'stats_reminder_sent_at')
    # ### end Alembic commands ###
