"""add processed_events idempotency table

Revision ID: 7f4302af1024
Revises: a224f97bc4d6
Create Date: 2026-08-06 12:20:52.035411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f4302af1024'
down_revision: Union[str, None] = 'a224f97bc4d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_events',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('handler_name', sa.String(length=255), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('event_id', 'handler_name')
    )
    # ### end Alembic commands ###
    # NOTE: autogenerate also proposed dropping 'ix_outbox_events_unpublished'
    # (same pre-existing drift noted in d45a3d5462bb and 35811ecfe0cf: that
    # partial index exists in the DB but isn't declared on the OutboxEvent
    # model) -- unrelated to this migration's purpose, left untouched again.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processed_events')
    # ### end Alembic commands ###
