"""add on_ice_skating and puck_handling target stats

Revision ID: 8d42e514b77f
Revises: 7f4302af1024
Create Date: 2026-08-06 12:55:46.389795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d42e514b77f'
down_revision: Union[str, None] = '7f4302af1024'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exercises', 'target_stat',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('strength', 'agility', 'intellect', 'endurance', 'on_ice_skating', 'puck_handling', name='target_stat', native_enum=False),
               existing_nullable=False)
    op.alter_column('skill_stat_weights', 'stat_type',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('strength', 'agility', 'intellect', 'endurance', 'on_ice_skating', 'puck_handling', name='target_stat', native_enum=False),
               existing_nullable=False)
    op.alter_column('stat_history', 'stat_type',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('strength', 'agility', 'intellect', 'endurance', 'on_ice_skating', 'puck_handling', name='target_stat', native_enum=False),
               existing_nullable=False)
    op.alter_column('user_stats', 'stat_type',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('strength', 'agility', 'intellect', 'endurance', 'on_ice_skating', 'puck_handling', name='target_stat', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###

    # Re-weight the 4 on-ice-relevant skills now that on_ice_skating/
    # puck_handling exist -- each skill's weights still sum to 1.0, same
    # convention as before (not DB-enforced: skill_stat_weights only has a
    # per-row CHECK on weight itself, ck_skill_stat_weights_weight_range,
    # no aggregate-per-skill constraint).
    op.execute(
        """
        UPDATE skill_stat_weights ssw
        SET weight = data.new_weight
        FROM (VALUES
            ('Катание', 'strength', 0.15),
            ('Катание', 'agility', 0.2),
            ('Катание', 'endurance', 0.15),
            ('Обводка', 'agility', 0.25),
            ('Обводка', 'intellect', 0.15),
            ('Баланс и устойчивость', 'strength', 0.2),
            ('Баланс и устойчивость', 'agility', 0.3),
            ('Мобильность', 'agility', 0.35),
            ('Мобильность', 'endurance', 0.15)
        ) AS data(skill_name, stat_type, new_weight)
        JOIN skills s ON s.name = data.skill_name
        WHERE ssw.skill_id = s.id AND ssw.stat_type = data.stat_type
        """
    )
    op.execute(
        """
        INSERT INTO skill_stat_weights (id, skill_id, stat_type, weight)
        SELECT gen_random_uuid(), s.id, data.stat_type, data.weight
        FROM (VALUES
            ('Катание', 'on_ice_skating', 0.5),
            ('Обводка', 'puck_handling', 0.6),
            ('Баланс и устойчивость', 'on_ice_skating', 0.5),
            ('Мобильность', 'on_ice_skating', 0.5)
        ) AS data(skill_name, stat_type, weight)
        JOIN skills s ON s.name = data.skill_name
        """
    )


def downgrade() -> None:
    # Reverse the data changes first -- the new stat_type values are longer
    # than VARCHAR(9), so shrinking the column below without removing rows
    # that use them would fail (or truncate) the ALTER COLUMN below.
    op.execute(
        """
        DELETE FROM skill_stat_weights ssw
        USING skills s
        WHERE ssw.skill_id = s.id
          AND ssw.stat_type IN ('on_ice_skating', 'puck_handling')
          AND s.name IN ('Катание', 'Обводка', 'Баланс и устойчивость', 'Мобильность')
        """
    )
    op.execute(
        """
        UPDATE skill_stat_weights ssw
        SET weight = data.old_weight
        FROM (VALUES
            ('Катание', 'strength', 0.3),
            ('Катание', 'agility', 0.5),
            ('Катание', 'endurance', 0.2),
            ('Обводка', 'agility', 0.6),
            ('Обводка', 'intellect', 0.4),
            ('Баланс и устойчивость', 'strength', 0.4),
            ('Баланс и устойчивость', 'agility', 0.6),
            ('Мобильность', 'agility', 0.7),
            ('Мобильность', 'endurance', 0.3)
        ) AS data(skill_name, stat_type, old_weight)
        JOIN skills s ON s.name = data.skill_name
        WHERE ssw.skill_id = s.id AND ssw.stat_type = data.stat_type
        """
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_stats', 'stat_type',
               existing_type=sa.Enum('strength', 'agility', 'intellect', 'endurance', 'on_ice_skating', 'puck_handling', name='target_stat', native_enum=False),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)
    op.alter_column('stat_history', 'stat_type',
               existing_type=sa.Enum('strength', 'agility', 'intellect', 'endurance', 'on_ice_skating', 'puck_handling', name='target_stat', native_enum=False),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)
    op.alter_column('skill_stat_weights', 'stat_type',
               existing_type=sa.Enum('strength', 'agility', 'intellect', 'endurance', 'on_ice_skating', 'puck_handling', name='target_stat', native_enum=False),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)
    op.alter_column('exercises', 'target_stat',
               existing_type=sa.Enum('strength', 'agility', 'intellect', 'endurance', 'on_ice_skating', 'puck_handling', name='target_stat', native_enum=False),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)
    # ### end Alembic commands ###
