"""team events, ice schedule template, one team per user

Revision ID: 904bf6990e49
Revises: 9e16be775b9b
Create Date: 2026-09-24 10:43:13.238476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '904bf6990e49'
down_revision: Union[str, None] = '9e16be775b9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_ice_schedule_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_ice_schedule_templates_team_id'), 'team_ice_schedule_templates', ['team_id'], unique=False)
    op.create_table('team_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('training', 'game', name='team_event_type', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'cancelled', name='team_event_status', native_enum=False), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('opponent_name', sa.String(length=100), nullable=True),
    sa.Column('source_template_id', sa.UUID(), nullable=True),
    sa.Column('board_status', sa.Enum('draft', 'published', name='team_event_publish_status', native_enum=False), nullable=True),
    sa.Column('lineup_status', sa.Enum('draft', 'published', name='team_event_publish_status', native_enum=False), nullable=False),
    sa.Column('last_nudge_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attendance_summary_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('board_not_ready_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_template_id'], ['team_ice_schedule_templates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_events_starts_at'), 'team_events', ['starts_at'], unique=False)
    op.create_index(op.f('ix_team_events_team_id'), 'team_events', ['team_id'], unique=False)
    op.drop_constraint(op.f('uq_team_memberships_team_user'), 'team_memberships', type_='unique')
    op.create_unique_constraint('uq_team_memberships_user', 'team_memberships', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_team_memberships_user', 'team_memberships', type_='unique')
    op.create_unique_constraint(op.f('uq_team_memberships_team_user'), 'team_memberships', ['team_id', 'user_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_team_events_team_id'), table_name='team_events')
    op.drop_index(op.f('ix_team_events_starts_at'), table_name='team_events')
    op.drop_table('team_events')
    op.drop_index(op.f('ix_team_ice_schedule_templates_team_id'), table_name='team_ice_schedule_templates')
    op.drop_table('team_ice_schedule_templates')
    # ### end Alembic commands ###
