"""coach reply feedback

Revision ID: 9513838373a6
Revises: eb44f8fc82a1
Create Date: 2026-10-04 13:59:21.850844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9513838373a6'
down_revision: Union[str, None] = 'eb44f8fc82a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coach_chat_messages', sa.Column('feedback_requested', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('coach_chat_messages', sa.Column('feedback', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coach_chat_messages', 'feedback')
    op.drop_column('coach_chat_messages', 'feedback_requested')
    # ### end Alembic commands ###
