"""add onice assessment flags to users

Revision ID: 9cff5e85daa6
Revises: 8d42e514b77f
Create Date: 2026-08-06 13:13:30.195264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cff5e85daa6'
down_revision: Union[str, None] = '8d42e514b77f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('has_onice_assessment', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('suggested_onice_reassessment', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'suggested_onice_reassessment')
    op.drop_column('users', 'has_onice_assessment')
    # ### end Alembic commands ###
