"""add training_blocks anchor_week_start_date

Revision ID: a224f97bc4d6
Revises: 35811ecfe0cf
Create Date: 2026-08-04 16:36:29.323367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a224f97bc4d6'
down_revision: Union[str, None] = '35811ecfe0cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_blocks', sa.Column('anchor_week_start_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###
    # NOTE: autogenerate also proposed dropping 'ix_outbox_events_unpublished'
    # (same pre-existing drift noted in d45a3d5462bb and 35811ecfe0cf: that
    # partial index exists in the DB but isn't declared on the OutboxEvent
    # model) -- unrelated to this migration's purpose, left untouched again.

    # Backfill: for each existing TrainingBlock, anchor_week_start_date is
    # the latest WeeklyPlan.week_start_date ever declared under it -- the
    # real calendar week its current week_in_block actually corresponds to.
    # A block with no WeeklyPlan at all (never actually used to plan a week)
    # keeps anchor_week_start_date NULL; _resolve_training_block treats that
    # as "first real planning call" rather than guessing a date.
    op.execute(
        """
        UPDATE training_blocks AS tb
        SET anchor_week_start_date = latest.max_week_start_date
        FROM (
            SELECT training_block_id, MAX(week_start_date) AS max_week_start_date
            FROM weekly_plans
            WHERE training_block_id IS NOT NULL
            GROUP BY training_block_id
        ) AS latest
        WHERE tb.id = latest.training_block_id
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_blocks', 'anchor_week_start_date')
    # ### end Alembic commands ###
