"""create exercises table

Revision ID: a9cee0cb30f9
Revises: d0c74a53ee79
Create Date: 2026-07-29 19:14:10.748463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9cee0cb30f9'
down_revision: Union[str, None] = 'd0c74a53ee79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('on_ice', 'off_ice', name='exercise_category', native_enum=False), nullable=False),
    sa.Column('phase', sa.Enum('warmup', 'main', 'cooldown', name='training_phase', native_enum=False), nullable=False),
    sa.Column('target_stat', sa.Enum('strength', 'agility', 'intellect', 'endurance', name='target_stat', native_enum=False), nullable=False),
    sa.Column('difficulty_level', sa.Integer(), nullable=False),
    sa.Column('equipment_type', sa.Enum('gym', 'home', 'bodyweight', name='equipment_type', native_enum=False), nullable=False),
    sa.Column('video_source_type', sa.String(length=50), nullable=True),
    sa.Column('video_source_id', sa.String(length=255), nullable=True),
    sa.CheckConstraint('difficulty_level >= 1 AND difficulty_level <= 5', name='ck_exercises_difficulty_level'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercises_name'), 'exercises', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exercises_name'), table_name='exercises')
    op.drop_table('exercises')
    # ### end Alembic commands ###
