"""add exercise admin_reviewed flag

Revision ID: ae98d105130e
Revises: 6a1d8f3c9b42
Create Date: 2026-08-31 07:42:40.959273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae98d105130e'
down_revision: Union[str, None] = '6a1d8f3c9b42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('admin_reviewed', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercises', 'admin_reviewed')
    # ### end Alembic commands ###
