"""phase 3 progress models and session block completion

Revision ID: b965117dd88b
Revises: 26272f98a1cd
Create Date: 2026-07-29 21:12:23.410428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b965117dd88b'
down_revision: Union[str, None] = '26272f98a1cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stat_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('stat_type', sa.Enum('strength', 'agility', 'intellect', 'endurance', name='target_stat', native_enum=False), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stat_history_user_id'), 'stat_history', ['user_id'], unique=False)
    op.create_table('training_streaks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('current_streak', sa.Integer(), server_default='0', nullable=False),
    sa.Column('longest_streak', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_activity_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_stats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('stat_type', sa.Enum('strength', 'agility', 'intellect', 'endurance', name='target_stat', native_enum=False), nullable=False),
    sa.Column('current_value', sa.Float(), server_default='0', nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'stat_type', name='uq_user_stats_user_stat_type')
    )
    op.create_index(op.f('ix_user_stats_user_id'), 'user_stats', ['user_id'], unique=False)
    op.add_column('session_blocks', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('xp', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('level', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'level')
    op.drop_column('users', 'xp')
    op.drop_column('session_blocks', 'completed_at')
    op.drop_index(op.f('ix_user_stats_user_id'), table_name='user_stats')
    op.drop_table('user_stats')
    op.drop_table('training_streaks')
    op.drop_index(op.f('ix_stat_history_user_id'), table_name='stat_history')
    op.drop_table('stat_history')
    # ### end Alembic commands ###
