"""widen years_of_experience to float

Revision ID: bea9b567adda
Revises: ff1cda08706f
Create Date: 2026-08-03 00:40:37.995488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bea9b567adda'
down_revision: Union[str, None] = 'ff1cda08706f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: autogenerate also proposed dropping 'ix_outbox_events_unpublished'
    # (same pre-existing drift noted in ff1cda08706f) -- unrelated here, left
    # untouched on purpose.
    op.alter_column('users', 'years_of_experience',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'years_of_experience',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
