"""add has_premium to users

Revision ID: d2ec9db23bcd
Revises: 3c1ea6d0c1f4
Create Date: 2026-08-08 17:32:07.158691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2ec9db23bcd'
down_revision: Union[str, None] = '3c1ea6d0c1f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('has_premium', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'has_premium')
    # ### end Alembic commands ###
