"""add exercise target volume fields

Revision ID: d45a3d5462bb
Revises: a1b2c3d4e5f6
Create Date: 2026-08-01 02:03:54.351984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd45a3d5462bb'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('target_sets', sa.Integer(), nullable=True))
    op.add_column('exercises', sa.Column('target_reps', sa.Integer(), nullable=True))
    op.add_column('exercises', sa.Column('target_duration_seconds', sa.Integer(), nullable=True))
    # ### end Alembic commands ###
    # NOTE: autogenerate also proposed dropping 'ix_outbox_events_unpublished'
    # (pre-existing drift: that partial index exists in the DB but isn't
    # declared on the OutboxEvent model) -- unrelated to this migration's
    # purpose, left untouched here on purpose.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercises', 'target_duration_seconds')
    op.drop_column('exercises', 'target_reps')
    op.drop_column('exercises', 'target_sets')
    # ### end Alembic commands ###
