"""add reference article image path

Revision ID: df9228b5f7f9
Revises: 9cff5e85daa6
Create Date: 2026-08-07 10:53:38.039621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df9228b5f7f9'
down_revision: Union[str, None] = '9cff5e85daa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reference_articles', sa.Column('image_path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reference_articles', 'image_path')
    # ### end Alembic commands ###
