"""add reference articles table

Revision ID: eb9f3868171f
Revises: d45a3d5462bb
Create Date: 2026-08-02 17:53:09.785176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb9f3868171f'
down_revision: Union[str, None] = 'd45a3d5462bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reference_articles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reference_articles_category'), 'reference_articles', ['category'], unique=False)
    # ### end Alembic commands ###
    # NOTE: autogenerate also proposed dropping 'ix_outbox_events_unpublished'
    # (pre-existing drift: that partial index exists in the DB but isn't
    # declared on the OutboxEvent model) -- unrelated to this migration's
    # purpose, left untouched here on purpose.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reference_articles_category'), table_name='reference_articles')
    op.drop_table('reference_articles')
    # ### end Alembic commands ###
