"""phase 2 weekly schedule tables and user equipment access

Revision ID: f8fe9ae20f27
Revises: a9cee0cb30f9
Create Date: 2026-07-29 19:41:14.109845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8fe9ae20f27'
down_revision: Union[str, None] = 'a9cee0cb30f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekly_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('week_start_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'week_start_date', name='uq_weekly_plans_user_week')
    )
    op.create_index(op.f('ix_weekly_plans_user_id'), 'weekly_plans', ['user_id'], unique=False)
    op.create_table('day_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('weekly_plan_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('session_type', sa.Enum('on_ice', 'off_ice', 'rest', name='day_session_type', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['weekly_plan_id'], ['weekly_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('weekly_plan_id', 'date', name='uq_day_plans_weekly_plan_date')
    )
    op.create_index(op.f('ix_day_plans_weekly_plan_id'), 'day_plans', ['weekly_plan_id'], unique=False)
    op.create_table('training_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('day_plan_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['day_plan_id'], ['day_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('day_plan_id')
    )
    op.create_table('session_blocks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('phase', sa.Enum('warmup', 'main', 'cooldown', name='training_phase', native_enum=False), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['training_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_blocks_session_id'), 'session_blocks', ['session_id'], unique=False)
    op.add_column('users', sa.Column('equipment_access', sa.Enum('gym', 'home', 'bodyweight', name='equipment_type', native_enum=False), server_default='bodyweight', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'equipment_access')
    op.drop_index(op.f('ix_session_blocks_session_id'), table_name='session_blocks')
    op.drop_table('session_blocks')
    op.drop_table('training_sessions')
    op.drop_index(op.f('ix_day_plans_weekly_plan_id'), table_name='day_plans')
    op.drop_table('day_plans')
    op.drop_index(op.f('ix_weekly_plans_user_id'), table_name='weekly_plans')
    op.drop_table('weekly_plans')
    # ### end Alembic commands ###
