"""add user profile fields and avatar

Revision ID: ff1cda08706f
Revises: eb9f3868171f
Create Date: 2026-08-02 20:02:08.359503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff1cda08706f'
down_revision: Union[str, None] = 'eb9f3868171f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_name', sa.String(length=100), server_default='', nullable=False))
    op.add_column('users', sa.Column('first_name', sa.String(length=100), server_default='', nullable=False))
    op.add_column('users', sa.Column('patronymic', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('jersey_number', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('avatar_path', sa.String(length=255), nullable=True))
    op.create_check_constraint(
        'ck_users_jersey_number',
        'users',
        'jersey_number IS NULL OR (jersey_number >= 0 AND jersey_number <= 99)',
    )
    # ### end Alembic commands ###
    # NOTE: autogenerate also proposed dropping 'ix_outbox_events_unpublished'
    # (pre-existing drift: that partial index exists in the DB but isn't
    # declared on the OutboxEvent model) -- unrelated to this migration's
    # purpose, left untouched here on purpose.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_users_jersey_number', 'users', type_='check')
    op.drop_column('users', 'avatar_path')
    op.drop_column('users', 'jersey_number')
    op.drop_column('users', 'patronymic')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'last_name')
    # ### end Alembic commands ###
