import uuid
from datetime import datetime, timezone

from sqlalchemy import func, or_, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.user import User
from app.schemas.user import UserCreate


class UserRepository:
    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    async def get_by_id(self, user_id: uuid.UUID) -> User | None:
        return await self._session.get(User, user_id)

    async def get_by_username(self, username: str) -> User | None:
        result = await self._session.execute(select(User).where(User.username == username))
        return result.scalar_one_or_none()

    async def get_by_email(self, email: str) -> User | None:
        result = await self._session.execute(select(User).where(User.email == email))
        return result.scalar_one_or_none()

    async def get_by_friend_code(self, friend_code: str) -> User | None:
        result = await self._session.execute(select(User).where(User.friend_code == friend_code))
        return result.scalar_one_or_none()

    async def create(
        self, user_in: UserCreate, password_hash: str, username: str, friend_code: str
    ) -> User:
        # AuthService.register already rejects the request before calling
        # this if user_in.privacy_consent is falsy, so reaching here means
        # consent was given -- timestamp it now rather than trusting a
        # client-supplied time. `username`/`friend_code` are generated by the
        # caller (AuthService._generate_username/_generate_friend_code)
        # rather than taken from user_in -- registration doesn't collect
        # either from the client.
        user = User(
            username=username,
            email=user_in.email,
            password_hash=password_hash,
            last_name=user_in.last_name,
            first_name=user_in.first_name,
            patronymic=user_in.patronymic,
            height=user_in.height,
            weight=user_in.weight,
            age=user_in.age,
            position=user_in.position,
            years_of_experience=user_in.years_of_experience,
            jersey_number=user_in.jersey_number,
            privacy_consent_at=datetime.now(timezone.utc),
            friend_code=friend_code,
        )
        self._session.add(user)
        await self._session.flush()
        return user

    async def list_users(
        self, *, search: str | None, limit: int, offset: int
    ) -> list[User]:
        stmt = select(User).order_by(User.created_at).limit(limit).offset(offset)
        if search is not None and search.strip() != "":
            pattern = f"%{search.strip()}%"
            stmt = stmt.where(
                or_(
                    User.email.ilike(pattern),
                    User.first_name.ilike(pattern),
                    User.last_name.ilike(pattern),
                )
            )
        result = await self._session.execute(stmt)
        return list(result.scalars().all())

    async def count_admins(self, *, exclude_user_id: uuid.UUID | None = None) -> int:
        stmt = select(func.count()).select_from(User).where(User.is_admin.is_(True))
        if exclude_user_id is not None:
            stmt = stmt.where(User.id != exclude_user_id)
        result = await self._session.execute(stmt)
        return result.scalar_one()
